### ISSUE TITLE
fail_fast: false still swallows exceptions

### ISSUE THREAD

**Issue by windiana42** [pydiverse/pydiverse.pipedag#34]
I am currently preparing example flow and example configuration for pipy packaging and the flow I produced (of course) did not work out of the box. The problem was that I couldn't see any reason why without `fail_fast: true`:

```
2023-01-14 12:49:21,893 [INFO] Connecting to localhost(127.0.0.1):2181, use_ssl: False
2023-01-14 12:49:21,902 [INFO] Zookeeper connection established, state: CONNECTED
2023-01-14 12:49:21,905 [INFO] Closing connection to localhost:2181
2023-01-14 12:49:21,905 [INFO] Zookeeper session closed, state: CLOSED
2023-01-14 12:49:21,907 [INFO] Connecting to localhost(127.0.0.1):2181, use_ssl: False
2023-01-14 12:49:21,910 [INFO] Zookeeper connection established, state: CONNECTED
1673696961.9106624 [info     ] start IPCServer                address=tcp://127.0.0.1:38801 cls=RunContextServer ctx_id=0 thread=28
1673696961.9107459 [info     ] Locking '_pipedag_setup_'      lock=ZooKeeperLockManager
1673696961.9343164 [info     ] Executing sql:
CREATE SCHEMA IF NOT EXISTS pipedag_metadata
1673696961.9366395 [info     ] Locking '<Stage: stage_1>'     lock=ZooKeeperLockManager
1673696961.9402406 [info     ] Locking '<Stage: stage_2>'     lock=ZooKeeperLockManager
1673696961.942848 [info     ] Unlocking '_pipedag_setup_'    lock=ZooKeeperLockManager
1673696961.9466767 [info     ] Executing sql:
CREATE SCHEMA IF NOT EXISTS stage_1
1673696961.9473195 [info     ] Executing sql:
DROP SCHEMA IF EXISTS stage_1__tmp CASCADE
1673696961.9486654 [info     ] Executing sql:
CREATE SCHEMA stage_1__tmp
/home/martin/.cache/pypoetry/virtualenvs/pydiverse-pipedag-Hmb_rarN-py3.10/lib/python3.10/site-packages/structlog/dev.py:427: UserWarning: Remove `format_exc_info` from your processor chain if you want pretty exceptions.
  warnings.warn(
1673696961.955855 [info     ] Failed to retrieve task from cache. task=<Task 'lazy_task_1' 0x7fa55f7a6980 (id: 0)>
Couldn't retrieve task from cache: <Task 'lazy_task_1' 0x7fa55f7a6980 (id: 0)>
1673696961.9574063 [warning  ] Task failed                    state=<FinalTaskState.FAILED: 2> task=<Task 'lazy_task_1' 0x7fa55f7a6980 (id: 0)>
1673696961.957739 [info     ] Unlocking '<Stage: stage_1>'   lock=ZooKeeperLockManager
1673696961.9597788 [info     ] Unlocking '<Stage: stage_2>'   lock=ZooKeeperLockManager
2023-01-14 12:49:21,962 [INFO] Closing connection to localhost:2181
2023-01-14 12:49:21,962 [INFO] Zookeeper session closed, state: CLOSED
1673696962.1574755 [info     ] stopped IPCServer              address=tcp://127.0.0.1:38801 cls=RunContextServer ctx_id=0 thread=28
Traceback (most recent call last):
  File "/home/martin/.config/JetBrains/PyCharm2022.3/scratches/scratch_14.py", line 51, in <module>
    main()
  File "/home/martin/.config/JetBrains/PyCharm2022.3/scratches/scratch_14.py", line 39, in main
    assert result.successful
AssertionError
```

With `fail_fast: true` I receive in addition:
```
Traceback (most recent call last):
  File "/home/martin/.config/JetBrains/PyCharm2022.3/scratches/scratch_14.py", line 51, in <module>
    main()
  File "/home/martin/.config/JetBrains/PyCharm2022.3/scratches/scratch_14.py", line 38, in main
    result = f.run()
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/core/flow.py", line 258, in run
    raise result.exception or Exception("Flow run failed")
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/engine/sequential.py", line 29, in run
    results[task] = task.run(
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/core/task.py", line 140, in run
    raise e
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/core/task.py", line 137, in run
    result = self._run(inputs)
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/core/task.py", line 163, in _run
    result = self.fn(*args, **kwargs)
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/core.py", line 268, in __call__
    result = store.materialize_task(task, result)
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/store.py", line 282, in materialize_task
    self._store_task_transaction(
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/store.py", line 372, in _store_task_transaction
    raise e
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/store.py", line 362, in _store_task_transaction
    store_metadata()
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/store.py", line 261, in store_metadata
    output_json = self.json_encode(m_value)
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/store.py", line 452, in json_encode
    return self.json_encoder.encode(value)
  File "/home/martin/progs/miniconda3/envs/poetry/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/martin/progs/miniconda3/envs/poetry/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/martin/PycharmProjects/pydiverse.pipedag/src/pydiverse/pipedag/materialize/util/json.py", line 67, in json_default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Select is not JSON serializable
```

**Comment by NMAC427** [comment]
Fixed by #85
